version: 0.9.{build}
image: Visual Studio 2019
configuration: Release
install:
- cmd: git submodule update --init
before_build:
- cmd: cd src
- cmd: nuget restore
build:
  project: src/OldRod.sln
  verbosity: minimal
artifacts:
- path: src/OldRod/bin/Release/net471
  name: net471